//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020/5/6 8:46:46
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Xin.Entities
{
    public partial class DingNew {

        public DingNew()
        {
            OnCreated();
        }

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int Id
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.StringLength(2147483647)]
        public virtual string OriginalContent
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.StringLength(2147483647)]
        public virtual string HtmlContent
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string Editer
        {
            get;
            set;
        }

        public virtual System.DateTime? CreateTime
        {
            get;
            set;
        }

        public virtual System.DateTime? UpdateTime
        {
            get;
            set;
        }

        public virtual DingClassify DingClassify
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
