//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020/6/3 15:50:40
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Xin.Entities
{
    public partial class DingNew {

        public DingNew()
        {
            this.Status = 0;
            OnCreated();
        }

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int Id
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.StringLength(2147483647)]
        public virtual string OriginalContent
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.StringLength(2147483647)]
        public virtual string HtmlContent
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string Editer
        {
            get;
            set;
        }

        public virtual System.DateTime? CreateTime
        {
            get;
            set;
        }

        public virtual System.DateTime? UpdateTime
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string Image
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string Title
        {
            get;
            set;
        }

        /// <summary>
        /// 状态: 0:保存 ; 1:发布 ;2:废弃
        /// </summary>
        public virtual int? Status
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.StringLength(2147483647)]
        public virtual string SubTitle
        {
            get;
            set;
        }

        public virtual DingClassify DingClassify
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
