//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020/5/28 8:41:23
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Xin.Entities
{
    public partial class BnsPaypalTransactionDetail {

        public BnsPaypalTransactionDetail()
        {
            this.BnsPaypalTransactionDetailsCartInfos = new List<BnsPaypalTransactionDetailsCartInfo>();
            OnCreated();
        }

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int Id
        {
            get;
            set;
        }

        /// <summary>
        /// 交易号
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoTransactionId
        {
            get;
            set;
        }

        /// <summary>
        /// 交易参考号
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoPaypalReferenceId
        {
            get;
            set;
        }

        /// <summary>
        /// 交易号状态
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoPaypalReferenceIdType
        {
            get;
            set;
        }

        /// <summary>
        /// 交易类型
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoTransactionEventCode
        {
            get;
            set;
        }

        /// <summary>
        /// 交易开始时间
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoTransactionInitiationDate
        {
            get;
            set;
        }

        /// <summary>
        /// 交易更新时间
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoTransactionUpdatedDate
        {
            get;
            set;
        }

        /// <summary>
        /// 交易币种
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoTransactionAmountCurrencyCode
        {
            get;
            set;
        }

        /// <summary>
        /// 交易总额
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoTransactionAmountValue
        {
            get;
            set;
        }

        /// <summary>
        /// 交易费用币种
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoFeeAmountCurrencyCode
        {
            get;
            set;
        }

        /// <summary>
        /// 交易费用
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoFeeAmountValue
        {
            get;
            set;
        }

        /// <summary>
        /// 营业税币种
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoSalesTaxAmountCurrencyCode
        {
            get;
            set;
        }

        /// <summary>
        /// 营业税
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoSalesTaxAmountValue
        {
            get;
            set;
        }

        /// <summary>
        /// 账户期末余额
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoEndingBalance
        {
            get;
            set;
        }

        /// <summary>
        /// 可用余额
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoAvailableBalance
        {
            get;
            set;
        }

        /// <summary>
        /// 交易状态
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoTransactionStatus
        {
            get;
            set;
        }

        /// <summary>
        /// 原始平台账单号
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoInvoiceId
        {
            get;
            set;
        }

        /// <summary>
        /// 保险费币种
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoInsuranceAmountCurrencyCode
        {
            get;
            set;
        }

        /// <summary>
        /// 保险费用
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoInsuranceAmountVlaue
        {
            get;
            set;
        }

        /// <summary>
        /// 运费币种
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoShippingAmountCurrencyCode
        {
            get;
            set;
        }

        /// <summary>
        /// 运费金额
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoShippingAmountValue
        {
            get;
            set;
        }

        /// <summary>
        /// 运费折扣币种
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoShippingDiscountAmountCurrencyCode
        {
            get;
            set;
        }

        /// <summary>
        /// 运费折扣费用
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoShippingDiscountAmountValue
        {
            get;
            set;
        }

        /// <summary>
        /// 交易主题
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoTransactionSubject
        {
            get;
            set;
        }

        /// <summary>
        /// 交易备注
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoTransactionNote
        {
            get;
            set;
        }

        /// <summary>
        /// 交易 自定义范围
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoCustomField
        {
            get;
            set;
        }

        /// <summary>
        /// 交易保护资格
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TransactionInfoProtectionEligibility
        {
            get;
            set;
        }

        /// <summary>
        /// paypa买家账户id
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string PayerInfoAccountId
        {
            get;
            set;
        }

        /// <summary>
        /// paypal 买家email
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string PayerInfoEmailAddress
        {
            get;
            set;
        }

        /// <summary>
        /// 买家手机号国家前缀
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string PayerInfoPhoneNumberCountryCode
        {
            get;
            set;
        }

        /// <summary>
        /// 买家手机号
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string PayerInfoPhoneNumberNationalNumber
        {
            get;
            set;
        }

        /// <summary>
        /// 买家地址状态
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string PayerInfoAddressStatus
        {
            get;
            set;
        }

        /// <summary>
        /// 买家状态
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string PayerInfoPayerStatus
        {
            get;
            set;
        }

        /// <summary>
        /// 买家姓名
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string PayerInfoPayerNameGivenName
        {
            get;
            set;
        }

        /// <summary>
        /// 买家姓
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string PayerInfoPayerNameSurname
        {
            get;
            set;
        }

        /// <summary>
        /// 买家备用的全名
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string PayerInfoPayerNameAlternateFullName
        {
            get;
            set;
        }

        /// <summary>
        /// 买家国家简称号
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string PayerInfoCountryCode
        {
            get;
            set;
        }

        /// <summary>
        /// 物流信息（收件人姓名）
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ShippingInfoName
        {
            get;
            set;
        }

        /// <summary>
        /// 地址第一行
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ShippingInfoAddressLine1
        {
            get;
            set;
        }

        /// <summary>
        /// 地址第二行
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ShippingInfoAddressLine2
        {
            get;
            set;
        }

        /// <summary>
        /// 城镇/城市
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ShippingInfoAddressCity
        {
            get;
            set;
        }

        /// <summary>
        /// 省/市/自治区/直辖市/特别行政区
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ShippingInfoAddressState
        {
            get;
            set;
        }

        /// <summary>
        /// 国家/地区
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ShippingInfoAddressCountryCode
        {
            get;
            set;
        }

        /// <summary>
        /// 邮政编码
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ShippingInfoAddressPostalCode
        {
            get;
            set;
        }

        /// <summary>
        /// 店铺标识
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ShopMark
        {
            get;
            set;
        }

        public virtual IList<BnsPaypalTransactionDetailsCartInfo> BnsPaypalTransactionDetailsCartInfos
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
