//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020/4/29 16:10:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Xin.Entities
{
    public partial class ResultTable {

        public ResultTable()
        {
            OnCreated();
        }

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int Id
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string Sku
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string CategoryParent
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string Category
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string Picture
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string Name
        {
            get;
            set;
        }

        public virtual int? UnicePeriodQty
        {
            get;
            set;
        }

        public virtual int? UncieToUsQty
        {
            get;
            set;
        }

        public virtual int? DhToUsQty
        {
            get;
            set;
        }

        public virtual int? UniceSaleQty
        {
            get;
            set;
        }

        public virtual int? UsTransAmazingQty
        {
            get;
            set;
        }

        public virtual int? OffLineQty
        {
            get;
            set;
        }

        public virtual int? UniceEndingQty
        {
            get;
            set;
        }

        public virtual int? UsEndingQty
        {
            get;
            set;
        }

        public virtual int? NomalEnndingQty
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
