//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020/5/12 14:53:08
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Xin.Common.CustomAttribute;

namespace Xin.Entities
{
    public partial class ECRepeatCust
    {

        public ECRepeatCust()
        {
            OnCreated();
        }
        [Excel(Header = "Id")]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int Id
        {
            get;
            set;
        }

        [Excel(Header = "平台")]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public virtual string PlateForm
        {
            get;
            set;
        }
        [Excel(Header = "店铺")]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public virtual string StoreName
        {
            get;
            set;
        }

        [Excel(Header = "处理月份")]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public virtual string DealMonth
        {
            get;
            set;
        }
        [Excel(Header = "邮箱")]

        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public virtual string Email
        {
            get;
            set;
        }

        [Excel(Header = "平台编码")]

        [System.ComponentModel.DataAnnotations.StringLength(100)]
        public virtual string PlateFormCode
        {
            get;
            set;
        }
        [Excel(Header = "金额")]

        public virtual decimal? Amount
        {
            get;
            set;
        }
        [Excel(Header = "付款时间")]

        public virtual System.DateTime? FkDate
        {
            get;
            set;
        }
        [Excel(Header = "付款类型")]

        [System.ComponentModel.DataAnnotations.StringLength(100)]
        public virtual string FkType
        {
            get;
            set;
        }
        [Excel(Header = "导入时间")]

        public virtual System.DateTime? Enterdate
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
