//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020/5/28 8:41:23
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Xin.Entities
{
    public partial class OmsOrderList {

        public OmsOrderList()
        {
            this.InventoryBatchOut = new List<OmsOrderListInventoryBatchOut>();
            this.Items = new List<OmsOrderListItem>();
            this.OrderFee = new List<OmsOrderListOrderFee>();
            OnCreated();
        }

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int Id
        {
            get;
            set;
        }

        /// <summary>
        /// 公司代码
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string CompanyCode
        {
            get;
            set;
        }

        /// <summary>
        /// 订单号
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string OrderCode
        {
            get;
            set;
        }

        /// <summary>
        /// 客户参考号
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ReferenceNo
        {
            get;
            set;
        }

        /// <summary>
        /// 平台
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string Platform
        {
            get;
            set;
        }

        /// <summary>
        /// 订单状态 C:待发货审核 W:待发货 D:已发货 H:暂存 N:异常订单 P:问题件 X:废弃
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string OrderStatus
        {
            get;
            set;
        }

        /// <summary>
        /// 运输方式
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ShippingMethod
        {
            get;
            set;
        }

        /// <summary>
        /// 跟踪号
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string TrackingNo
        {
            get;
            set;
        }

        /// <summary>
        /// 仓库Id
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string WarehouseId
        {
            get;
            set;
        }

        /// <summary>
        /// 仓库代码
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string WarehouseCode
        {
            get;
            set;
        }

        /// <summary>
        /// 订单说明
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string OrderDesc
        {
            get;
            set;
        }

        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual System.DateTime? DateCreate
        {
            get;
            set;
        }

        /// <summary>
        /// 审核时间
        /// </summary>
        public virtual System.DateTime? DateRelease
        {
            get;
            set;
        }

        /// <summary>
        /// 出库时间
        /// </summary>
        public virtual System.DateTime? DateShipping
        {
            get;
            set;
        }

        /// <summary>
        /// 修改时间
        /// </summary>
        public virtual System.DateTime? DateModify
        {
            get;
            set;
        }

        /// <summary>
        /// 收件人国家二字码
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ConsigneeCountryCode
        {
            get;
            set;
        }

        /// <summary>
        /// 收件人国家
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ConsigneeCountryName
        {
            get;
            set;
        }

        /// <summary>
        /// 省
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ConsigneeState
        {
            get;
            set;
        }

        /// <summary>
        /// 城市
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ConsigneeCity
        {
            get;
            set;
        }

        /// <summary>
        /// 区域
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ConsigneeDistrict
        {
            get;
            set;
        }

        /// <summary>
        /// 地址1
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ConsigneeStreet1
        {
            get;
            set;
        }

        /// <summary>
        /// 地址2
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ConsigneeStreet2
        {
            get;
            set;
        }

        /// <summary>
        /// 地址3
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ConsigneeStreet3
        {
            get;
            set;
        }

        /// <summary>
        /// 邮编
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ConsigneZipcode
        {
            get;
            set;
        }

        /// <summary>
        /// 门牌号
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ConsigneeDoorplate
        {
            get;
            set;
        }

        /// <summary>
        /// 公司
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ConsigneeCompany
        {
            get;
            set;
        }

        /// <summary>
        /// 收件人名称
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ConsigneeName
        {
            get;
            set;
        }

        /// <summary>
        /// 收件人电话
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ConsigneePhone
        {
            get;
            set;
        }

        /// <summary>
        /// 收件人邮箱
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ConsigneeEmail
        {
            get;
            set;
        }

        /// <summary>
        /// 异常信息
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string AbnormalReason
        {
            get;
            set;
        }

        /// <summary>
        /// 第三方渠道承运商
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string CourierName
        {
            get;
            set;
        }

        /// <summary>
        /// 渠道代码
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string ChannelCode
        {
            get;
            set;
        }

        /// <summary>
        /// COD订单：0:否 1:是
        /// </summary>
        public virtual int? IsOrderCod
        {
            get;
            set;
        }

        /// <summary>
        /// COD币种
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string OrderCodCurrency
        {
            get;
            set;
        }

        /// <summary>
        /// 订单重量
        /// </summary>
        public virtual decimal? OrderWeight
        {
            get;
            set;
        }

        /// <summary>
        /// COD Value
        /// </summary>
        public virtual decimal? OrderCodPrice
        {
            get;
            set;
        }

        public virtual OmsOrderListFeeSummery FeeSummery
        {
            get;
            set;
        }

        public virtual IList<OmsOrderListInventoryBatchOut> InventoryBatchOut
        {
            get;
            set;
        }

        public virtual IList<OmsOrderListItem> Items
        {
            get;
            set;
        }

        public virtual IList<OmsOrderListOrderFee> OrderFee
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
