//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-02-05 09:46:35
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Justable
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Xin.ExternalService.EC.Response.Model
{

    public partial class EC_OrderConfigDatas
    {
        /// <summary>
        /// 平台订单ID
        /// </summary>

        public string OriginalOrderId { get; set; }
        /// <summary>
        /// 平台账号,目前只支持ebay平台
        /// </summary>

        public string OriginalAccount { get; set; }
        /// <summary>
        /// 原始订单数据json字符串,目前只支持ebay平台
        /// </summary>

        public string EbayOrders { get; set; }
        /// <summary>
        /// 	原始订单明细数据json字符串,目前只支持ebay平台
        /// </summary>

        public string EbayOrderDetail { get; set; }

    }
}

