//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-02-05 09:46:35
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Justable
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Xin.ExternalService.EC.Response.Model
{

    public partial class EC_ProductBox
    {
        /// <summary>
        /// 名称
        /// </summary>

        public string BoxName { get; set; }
        /// <summary>
        /// 英文名称

        /// </summary>

        public string boxNameEn { get; set; }
        /// <summary>
        /// 长
        /// </summary>

        public decimal? boxLength { get; set; }
        /// <summary>
        /// 宽
        /// </summary>

        public decimal? boxWidth { get; set; }
        /// <summary>
        /// 高
        /// </summary>

        public decimal? boxHeight { get; set; }
        /// <summary>
        /// 重量
        /// </summary>

        public decimal? boxWeight { get; set; }
        /// <summary>
        /// 数量
        /// </summary>

        public int? quantity { get; set; }
        /// <summary>
        /// 箱规状态： 0不可用 1可用

        /// </summary>

        public int? boxStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>

        public string ProductSku { get; set; }
        public EC_Product EC_ProductE { get; set; }

    }
}

