//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-02-05 09:46:35
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Justable
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Xin.ExternalService.EC.Response.Model
{
    public partial class EC_ProductCombination
    {
        /// <summary>
        /// FNSKU

        /// </summary>

        public string PcrFnsku { get; set; }
        /// <summary>
        /// FBA-ASIN
        /// </summary>

        public string PcrFbaAsin { get; set; }
        /// <summary>
        /// 仓库Id，0为全部仓库
        /// </summary>

        public string WarehouseId { get; set; }
        /// <summary>
        /// 创建时间

        /// </summary>

        public DateTime? PcrAddTime { get; set; }
        /// <summary>
        /// 更新时间

        /// </summary>

        public DateTime? PcrUpdateTime { get; set; }
        /// <summary>
        /// 产品Sku
        /// </summary>

        public string ProductSku { get; set; }

        public List<EC_SubProducts> SubProducts { get; set; }

    }
}

