//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-02-05 09:46:35
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Justable
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Xin.ExternalService.EC.Response.Model
{

    public partial class EC_ProductCustomCategory
    {
        /// <summary>
        /// 自定义分类名称
        /// </summary>

        public string PucName { get; set; }
        /// <summary>
        /// 
        /// </summary>

        public string ProductSku { get; set; }

    }
}

