//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-02-05 09:46:35
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Justable
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Xin.ExternalService.EC.Response.Model
{
    public partial class EC_SalesOrderAddress
    {
        /// <summary>
        /// 主键
        /// </summary>

        public string ShippingAddressId { get; set; }
        /// <summary>
        /// 收件人名称
        /// </summary>

        public string Name { get; set; }
        /// <summary>
        /// 公司名称
        /// </summary>

        public string CompanyName { get; set; }
        /// <summary>
        /// 国家二字码
        /// </summary>

        public string CountryCode { get; set; }
        /// <summary>
        /// 国家名称
        /// </summary>

        public string CountryName { get; set; }
        /// <summary>
        /// 城市名称
        /// </summary>

        public string CityName { get; set; }
        /// <summary>
        /// 邮编
        /// </summary>

        public string PostalCode { get; set; }
        /// <summary>
        /// 地址第一行
        /// </summary>

        public string Line1 { get; set; }
        /// <summary>
        /// 地址第二行
        /// </summary>

        public string Line2 { get; set; }
        /// <summary>
        /// 地址第三行
        /// </summary>

        public string Line3 { get; set; }
        /// <summary>
        /// 区
        /// </summary>

        public string District { get; set; }
        /// <summary>
        /// 州或省
        /// </summary>

        public string State { get; set; }
        /// <summary>
        /// 门牌号
        /// </summary>

        public string Doorplate { get; set; }
        /// <summary>
        /// 电话
        /// </summary>

        public string Phone { get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>

        public DateTime? CreatedDate { get; set; }
        /// <summary>
        /// 更新时间
        /// </summary>

        public DateTime? UpdateDate { get; set; }

    }
}

