//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-02-05 09:46:35
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Justable
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Xin.ExternalService.EC.Response.Model
{
    public partial class EC_Warehouse
    {
        /// <summary>
        /// 仓库ID
        /// </summary>

        public int WarehouseId { get; set; }
        /// <summary>
        /// 仓库代码
        /// </summary>

        public string WarehouseCode { get; set; }
        /// <summary>
        /// 仓库名称
        /// </summary>

        public string WarehouseDesc { get; set; }
        /// <summary>
        /// 仓库类型：0标准，1中转
        /// </summary>

        public int? WarehouseType { get; set; }
        /// <summary>
        /// 状态：-1已废弃,0不可用,1可用
        /// </summary>

        public int? WarehouseStatus { get; set; }
        /// <summary>
        /// 运营方式：0自营,1第三方
        /// </summary>

        public int? WarehouseVirtual { get; set; }
        /// <summary>
        /// 第三方仓储服务
        /// </summary>

        public string WarehouseService { get; set; }
        /// <summary>
        /// 是否需要头程（应用于库存成本是否包含头程费用）:0否,1是
        /// </summary>

        public int? IsTransfer { get; set; }
        /// <summary>
        /// 国家二字码
        /// </summary>

        public string CountryCode { get; set; }
        /// <summary>
        /// 国家ID
        /// </summary>

        public int? CountryId { get; set; }
        /// <summary>
        /// 省份
        /// </summary>

        public string State { get; set; }
        /// <summary>
        /// 城市
        /// </summary>

        public string City { get; set; }
        /// <summary>
        /// 联系人
        /// </summary>

        public string Contacter { get; set; }
        /// <summary>
        /// 公司名称
        /// </summary>

        public string Company { get; set; }
        /// <summary>
        /// 电话
        /// </summary>

        public string PhoneNo { get; set; }
        /// <summary>
        /// 地址1
        /// </summary>

        public string StreetAddress1 { get; set; }
        /// <summary>
        /// 地址2
        /// </summary>

        public string StreetAddress2 { get; set; }
        /// <summary>
        /// 邮编
        /// </summary>

        public string Postcode { get; set; }
        /// <summary>
        /// 门牌号
        /// </summary>

        public string StreetNumber { get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>

        public DateTime? WarehouseAddTime { get; set; }
        /// <summary>
        /// 最后更新时间
        /// </summary>
        public DateTime? WarehouseUpdateTime { get; set; }

    }
}

